import { cookies } from "next/headers";
import Image from "next/image";
import type { ReactNode } from "react";
import "~/styles/globals.css";
import { TRPCReactProvider } from "~/trpc/react";
import { alegrea, mulish } from "./fonts";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body
        className={`bg-darkgray font-p text-smoke ${mulish.variable} ${alegrea.variable}`}
      >
        <TRPCReactProvider cookies={cookies().toString()}>
          <LayoutBg>{children}</LayoutBg>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

const LayoutBg = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <div className="fixed z-0 h-full w-full">
        <Image className="object-cover" src="/bg.jpg" alt="Фон" fill />
      </div>

      <div className="relative z-10 flex min-h-[100lvh] flex-col justify-between bg-darkgray/70">
        {children}
      </div>

      <div id="modal" />
    </>
  );
};
